export const styles = [
  'Anime',
  'Neon Punk',
  'GTA',
  'Photographic',
  'Pixel Art',
  'Analog Film',
  'Cinematic',
  'Comic Book',
  'Cubist',
  'Digital Art',
  'Enhance',
  'Fantasy Art',
  'Origami',
  '3D Model'
] as const;
/*
[
  '3D Model',
  'Analog Film',
  'Anime',
  'Cinematic',
  'Comic Book',
  'Craft Clay',
  'Digital Art',
  'Enhance',
  'Fantasy Art',
  'Isometric Style',
  'Line Art',
  'Lowpoly',
  'Neon Punk',
  'Origami',
  'Photographic',
  'Pixel Art',
  'Texture',
  'Advertising',
  'Food Photography',
  'Real Estate',
  'Abstract',
  'Cubist',
  'Graffiti',
  'Hyperrealism',
  'Impressionist',
  'Pointillism',
  'Pop Art',
  'Psychedelic',
  'Renaissance',
  'Steampunk',
  'Surrealist',
  'Typography',
  'Watercolor',
  'Fighting Game',
  'GTA',
  'Super Mario',
  'Minecraft',
  'Pokémon',
  'Retro Arcade',
  'Retro Game',
  'RPG Fantasy Game',
  'Strategy Game',
  'Street Fighter',
  'Legend of Zelda',
  'Architectural',
  'Disco',
  'Dreamscape',
  'Dystopian',
  'Fairy Tale',
  'Gothic',
  'Grunge',
  'Horror',
  'Minimalist',
  'Monochrome',
  'Nautical',
  'Space',
  'Stained Glass',
  'Techwear Fashion',
  'Tribal',
  'Zentangle',
  'Collage',
  'Flat Papercut',
  'Kirigami',
  'Paper Mache',
  'Paper Quilling',
  'Papercut Collage',
  'Papercut Shadow Box',
  'Stacked Papercut',
  'Thick Layered Papercut',
  'Alien',
  'Film Noir',
  'HDR',
  'Long Exposure',
  'Neon Noir',
  'Silhouette',
  'Tilt-Shift'
] as const; */

export type Styles = (typeof styles)[number];
